### ISSUE TITLE
Ios connection problem

### ISSUE THREAD

**Issue by ismailgzn** [vavadiyahiren/xmpp_plugin#54]
Hi brother,
First of all thank you for this great plugin.
I am developing a chat app using xmpp ejabberd server. And I implemented your plugin in the app. at the beginning everything is ok and messaging was really fast for both OS(iOS and android). But 2 days ago iOS connection is cutted suddenly even though I did nothing. 
The strange thing is this android connection has no problem against iOS. Everything is good in android.
Unfurtunately I couldn't understand the reason of the problem which is in iOS. How can we repair this?
Please help us..

**Comment by vavadiyahiren** [comment]
Can you see anything on logs and paste it here ? 

Same user works fine for android but not for ios ? 

Please share some more details to investigate.

**Comment by ismailgzn** [comment]
Unfortunately I couldn't see anything on logs. 
Just have seen "onConnectionEvents ~~>>{type: XmppConnectionState.disconnected, error: }".
If you could test your own xmpp_plugin example app on ios. 
I think you will get the same error and you will not connect to server.
Could you try it?

**Comment by vavadiyahiren** [comment]
I will try and update if required, However you can test with the latest version and let me know if that doens't work.

If you can send me your server hostname and one test creds i can test with your server space since it is working for me here.

**Comment by ismailgzn** [comment]
ok.
"user_jid" -> "[905534163888@grafen.org/iOS](http://905534163888@grafen.org/iOS)"
"password" -> "6ZXhjw9s8QXSO7I4VTi1"
"host" -> "[grafen.org](http://grafen.org/)"
"port" -> "5222"

connected with these creds on android but disconnected on ios.

**Comment by ismailgzn** [comment]
Nothing is changed about the problem. Do you work on it?

**Comment by vavadiyahiren** [comment]
@ismailgzn Working on it, Should've been fixed this week.

**Comment by SajithSJLeaderGroup** [comment]
Hi, same problem here with iOS. Any update on this issue?

**Comment by piccotalent-127** [comment]
Hello, Thanks for your wonderful plugin but it is not working in IOS it is throwing the same error as the one mentioned above and there is no reason or cause of the error in log can you please check that

**Comment by matt3oromani** [comment]
i had the same problem and was a problem with DNS server.

**Comment by chupchep** [comment]
Hi bro, i had same problem :(

**Comment by vavadiyahiren** [comment]
Fixed in latest version 2.1.11

**Comment by kamil-kmetyk** [comment]
Hi, @vavadiyahiren it seems that the issue is back. I experience the same troubles as @ismailgzn - I can connect using Android device, but can't with iOS with the same credentials.

Log file for iOS:
```
Time: 2024-05-18 14:19:05.7130
Action: methodReceiveFromFlutter
NativeMethod: login
Content: Optional({
    autoDeliveryReceipt = 1;
    automaticReconnection = 1;
    host = "my-host";
    nativeLogFilePath = "some/path/to/Documents/xmpp_logs";
    password = xyz;
    port = 5222;
    requireSSLConnection = 1;
    useStreamManagement = 1;
    "user_jid" = "6c71b096-d3f0-40aa-a1cc-69189dbc57f4@some-domain/iOS";
})


Time: 2024-05-18 14:19:05.7140
Action: methodReceiveFromFlutter
NativeMethod: get_connection_status
Content: nil
```

Only entry in dev console is this one:
```
flutter: >> onConnectionEvents: XmppConnectionState.disconnected
```

Also I've extend my Info.plist with code below (however, ejabberd is using ssl).
```xml
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>my-domain-here</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSTemporaryExceptionMinimumTLSVersion</key>
				<string>TLSv1.0</string>
			</dict>
		</dict>
	</dict>
```

Tested on 2.2.12

**Comment by kamil-kmetyk** [comment]
Ok, I found the solution... but I'm not a Swift dev, so I can't provide a valid fix. But looks like `ios/Classes/FlutterXmppPlugin.swift` and it's method `performLoginActivity` is looking for **String** for port, while in most cases what's Flutter giving is **int**.

So "temporary" solution is to fix Flutter part of the code to something like
```dart
    _auth = {
      'user_jid': 'user@server/resource',
      'password': 'mysterious-secrets',
      'host': 'host',
      'port': '5222', <<<<<<<<<<<<< set port as string instead of integer
    };

    _connection = XmppConnection(_auth);
```

**Comment by emirmg** [comment]
I had faced same issue here. Its not solved by setting port as a string.

Sometimes connection fails and i got disconnected message and sometimes its authenticated successfully but some features like MUC not working properly on just iOS.

Everything is ok on android.
